spring:
  thymeleaf:
    mode: HTML
  profiles:
    active: dev

# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# mybatis

mybatis:
  configuration:
    map-underscore-to-camel-case: true
