# 生产环境
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?servertimezone=UTC
    data-username: root
    data-password: qhw739t

server:
  port: 8081
mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    root: info
    com.kc345ws: debug
